### ISSUE TITLE
what about a new sensor noise generation?

### ISSUE THREAD

**Issue by oneTaken** [arcchang1236/CA-NoiseGAN#2]
Hi, nice and solid work.  

And I have a question about new sensor noise generation.  

I do not find something related to **specific sensor parameters** in inference phase in Fig 1.   
It seems that If I have a new sensor, I have to retrained the **whole** model. The previous trained model seems hard to just **tuning** well for a new sensor data.  

Besides, In just **one sensor** situation.  
From Table 1 and Table 2, If I just have only one sensor, the triplet loss can not be used. And Table 1 should be modified as follow:  

||Gaussian| Posisson-Gaussian|Noise Flow|Ours|
|:--:|:--:|:--:|:--:|:--:|
|D_KL|0.54707|0.01006|0.00912|0.01374|

It seems that this camera-aware pipeline is worse than **Noise Flow**.  

Thx.

**Comment by arcchang1236** [comment]
Hi,

**In our work, we use the initial synthetic noise and the camera-encoding network to achieve camera-awareness without additional parameters. You can see the Section 3. of paper and long video for more detail first.**

As you said, our work cannot generate real-world noise of unseen cameras well since our network needs sufficient data for training. However, **in Table. 6, we proved our model can have competitive results when using fewer data**. Generating real-world noise of unseen camera is involved in domain adaption task. We start to do some experiments on one-shot noise generation and some meta-learning skills of adapting to new cameras now.

For the second consideration, you misunderstood the table. Table 1. is the average KL-divergence of each camera. So **if you only train on one camera, you cannot ask to get the same performance in other cameras** . For Noise Flow, they cannot get good results in other cameras when only training on one camera. For PG noise, it still needs sufficient data of specific camera to calibrate the parameters. 

[This link](https://drive.google.com/file/d/1Z0dgXD8ZnJuqdQqg2IqHKgAZydqmb0B2/view?usp=sharing) is one experiment of our model without the camera-encoding network. We train on a specific camera and test on each camera. You can see the model can get better performance in the same camera than PG with calibration, other cameras are worse than PG. (x-axis: idx of the test image, y-axis: KL-divergence)


By the way, We use **"camera"** instead of **"sensor"** in our papers since the SIDD dataset didn't provide the specific information of the sensor.

Hope this will be helpful to you.
  

Arc
